CREATE TABLE Notification (
	listing_id INT FOREIGN KEY REFERENCES Listing(id) PRIMARY KEY,
	belongs_to VARCHAR(20) FOREIGN KEY REFERENCES UserInfo(username) NOT NULL,
	price FLOAT NOT NULL
);

ALTER TABLE Notification
DROP CONSTRAINT PK__Notifica__89D81774D6AA20F7;

ALTER TABLE Notification
ADD id INT IDENTITY(1,1) PRIMARY KEY;