CREATE TABLE Report(
	id INT IDENTITY(1,1) PRIMARY KEY,
	submitted_by VARCHAR(20) FOREIGN KEY REFERENCES UserInfo(username) NOT NULL,
	refers_to VARCHAR(20) FOREIGN KEY REFERENCES Creator(username) NOT NULL,
	reason VARCHAR(15) NOT NULL,
	date DATE NOT NULL,
	description VARCHAR(MAX)
);