CREATE TABLE Reward (
	id INT IDENTITY(1,1) PRIMARY KEY,
	name VARCHAR(40) NOT NULL,
	price_in_points INT NOT NULL,
	offered_by VARCHAR(20) FOREIGN KEY REFERENCES Creator(username) NOT NULL
);

CREATE TABLE RewardPoint (
	client VARCHAR(20) FOREIGN KEY REFERENCES UserInfo(username) NOT NULL,
	creator VARCHAR(20) FOREIGN KEY REFERENCES Creator(username) NOT NULL,
	points NUMERIC NOT NULL DEFAULT(0),
	PRIMARY KEY(client,creator)
);
